"""empty message

Revision ID: 9122e9c4325d
Revises: a7dc34ccf788
Create Date: 2020-02-26 23:11:45.786722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9122e9c4325d'
down_revision = 'a7dc34ccf788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'actor', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actor', type_='unique')
    # ### end Alembic commands ###
